name: Publish Image
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and publish image to GitHub Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: eci-ux/smoke-tests-container/smoke-tests-container
        username: eci-ux
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
